# Generated by Django 5.2.9 on 2026-01-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_costumuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('DOCTOR', 'doctor'), ('PATIENT', 'patient')], default='PATIENT', max_length=15),
        ),
    ]
