# Generated by Django 5.2.9 on 2026-01-04 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_patientprofile_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientProfile',
            new_name='ProfilePatient',
        ),
    ]
